### ISSUE TITLE
java.lang.NoSuchFieldError: field with Groovy 3.0

### ISSUE THREAD

**Issue by injecteer** [grails/gorm-mongodb#113]
Using GORM-standalone, JDK 1.8.0_181 and the dependencies:

```
String groovyVer = '3.0.3'
String gormVer = '7.0.0.RELEASE'

dependencies{
  compile "org.grails:grails-datastore-gorm-mongodb:$gormVer"
  compile "org.grails:grails-datastore-gorm-mongodb-ext:$gormVer"
  compile "org.codehaus.groovy:groovy:$groovyVer"
  compile "org.codehaus.groovy:groovy-json:$groovyVer"
}
```

the code 
```
MongoDatastore init(){
  new MongoDatastore( config, *domainClasses )
}
```

throws the exception:
```
java.lang.NoSuchFieldError: field
	at org.grails.datastore.mapping.reflect.ClassPropertyFetcher.getDeclaredField(ClassPropertyFetcher.java:421)
	at org.grails.datastore.mapping.model.config.GormMappingConfigurationStrategy.getPersistentProperties(GormMappingConfigurationStrategy.java:177)
	at org.grails.datastore.mapping.model.config.JpaMappingConfigurationStrategy.getPersistentProperties(JpaMappingConfigurationStrategy.java:35)
	at org.grails.datastore.mapping.model.AbstractPersistentEntity.initialize(AbstractPersistentEntity.java:134)
	at org.grails.datastore.mapping.model.AbstractMappingContext.initializePersistentEntity(AbstractMappingContext.java:352)
	at org.grails.datastore.mapping.model.AbstractMappingContext.addPersistentEntities(AbstractMappingContext.java:283)
	at org.grails.datastore.mapping.mongo.config.MongoMappingContext.initialize(MongoMappingContext.java:255)
	at org.grails.datastore.mapping.mongo.config.MongoMappingContext.<init>(MongoMappingContext.java:137)
	at org.grails.datastore.mapping.mongo.MongoDatastore.createMappingContext(MongoDatastore.java:941)
	at org.grails.datastore.mapping.mongo.MongoDatastore.<init>(MongoDatastore.java:247)
	at org.grails.datastore.mapping.mongo.MongoDatastore.<init>(MongoDatastore.java:359)
	at org.grails.datastore.mapping.mongo.MongoDatastore.<init>(MongoDatastore.java:369)
	at org.grails.datastore.mapping.mongo.MongoDatastore.<init>(MongoDatastore.java:411)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:59)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite.callConstructor(ConstructorSite.java:45)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at io.mozaiq.BootStrap.init(BootStrap.groovy:39)
```

By setting 
```
String groovyVer = '2.5.11'
```
the problem disappears

**Comment by puneetbehl** [comment]
The GORM for MongoDB 7.0.0 does not support Groovy 3. It will be supported in the v7.1.0.

**Comment by injecteer** [comment]
@puneetbehl has it been fixed?

**Comment by puneetbehl** [comment]
Please use 7.1.0.M1 for Groovy 3 support

**Comment by injecteer** [comment]
@puneetbehl 7.1.0.M1 works like a charm, thanx!
