### ISSUE TITLE
Mongo document attrribute "collection" on domain objects not resolving

### ISSUE THREAD

**Issue by amitdk** [grails/gorm-mongodb#133]
With Grails 4.0.3 and Mongo plugin 6.1.7, domain objects mapped to Mongo collections do not correctly resolve their "collection" attribute. The call to retrieve the Document instance on the "collection" property essentially fails with the following error:

groovy.lang.MissingPropertyException: No such property: collection for class: Product
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.staticPropertyMissing(GormEntity.groovy:790)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

The following code fails:
Product.collection.find(eq("title", "coffee")).first()

Under the covers, it looks like the DataStoreQualifiers aren't getting correctly setup for MongoEntities. So, in the above case where the qualifier is "collection", it returns an empty connectionSource, instead of returning the Mongo connection source.

**Comment by puneetbehl** [comment]
Please use the version 7.0.0 with Grails 4. See https://github.com/grails/gorm-mongodb/releases/tag/v7.0.0 for more details.

**Comment by puneetbehl** [comment]
Closed due to lack of feedback.
