### ISSUE TITLE
Saving Mongo document with embedded object(s) throws BsonInvalidOperationException

### ISSUE THREAD

**Issue by temi** [grails/gorm-mongodb#178]
### Issue
Saving a domain object with embedded object fails with  `org.bson.BsonInvalidOperationException`. The stack trace is given below. Underlying issue is Groovy trying to convert a BSON Document to boolean [here](https://github.com/grails/gorm-mongodb/blob/v6.1.7/grails-datastore-gorm-mongodb/src/main/groovy/org/grails/datastore/mapping/mongo/engine/codecs/PersistentEntityCodec.groovy#L374). 

### Stack trace
```
Caused by: org.bson.BsonInvalidOperationException: Value expected to be of type BOOLEAN is of unexpected type DOCUMENT
	at org.bson.BsonValue.throwIfInvalidType(BsonValue.java:419)
	at org.bson.BsonValue.asBoolean(BsonValue.java:139)
	at org.grails.datastore.mapping.mongo.engine.codecs.PersistentEntityCodec.encodeEmbeddedCollectionUpdate(PersistentEntityCodec.groovy:374)
	at org.grails.datastore.mapping.mongo.engine.codecs.PersistentEntityCodec.encodeUpdate(PersistentEntityCodec.groovy:254)
	at org.grails.datastore.mapping.mongo.MongoCodecSession.flush(MongoCodecSession.groovy:158)
	at org.grails.datastore.mapping.mongo.AbstractMongoSession.flush(AbstractMongoSession.java:74)
	at org.grails.datastore.gorm.GormInstanceApi.doSave(GormInstanceApi.groovy:368)
	at org.grails.datastore.gorm.GormInstanceApi$_save_closure5.doCall(GormInstanceApi.groovy:180)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:319)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:40)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:179)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:151)
	at au.org.ala.profile.BaseDataAccessService.save(BaseDataAccessService.groovy:10)
	at au.org.ala.profile.ProfileService.$tt__updateAttribute(ProfileService.groovy:1183)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at au.org.ala.profile.AttributeController.update(AttributeController.groovy:63)
```
### Software versions
Grails 3.3.11
Mongodb plugin 6.1.7
Mongodb driver 3.9.1
Mongo version 4.0

**Comment by temi** [comment]
I worked around this issue by adding the below code in Bootstrap.groovy.
```
BsonDocument.metaClass.asBoolean = {
         !delegate.isEmpty()
}
```

**Comment by puneetbehl** [comment]
This must be fixed in GORM 7.
