### ISSUE TITLE
Unique constraint on multiple fields fails unit tests

### ISSUE THREAD

**Issue by bleurubin** [grails/gorm-mongodb#34]
When using a domain object that has a unique constraint on multiple fields unit tests fail.  The application successfully runs and enforces the constraint, the issue is just with unit tests.  The same unit tests succeed using hibernate.  The error is:

```
Cannot cast object 'org.grails.datastore.gorm.GormStaticApi@7af24f66' with class 'org.grails.datastore.gorm.GormStaticApi' to class 'org.grails.datastore.gorm.mongo.api.MongoStaticApi'
```

For example, a domain class Foo:
```
class Foo {

    String name
    String value

    static constraints = {
        name unique: ['value']
    }
}
```

with a corresponding FooSpec test:
```
@TestFor(Foo)
@Mock(Foo)
class FooSpec extends Specification {

    def setup() {
    }

    def cleanup() {
    }

    void "test save"() {
        given:
        new Foo(name: 'foo1', value: 'val1').save(flush:true, failOnError:true)

        expect:
            Foo.count == 1
    }
}
```

Code is here:  https://github.com/bleurubin/testapp/tree/mongo-unique-constraint-bug

Hibernate version that passes here: https://github.com/bleurubin/testapp/tree/hibernate-unique-constraint

Full stacktrace:

```
Cannot cast object 'org.grails.datastore.gorm.GormStaticApi@7af24f66' with class 'org.grails.datastore.gorm.GormStaticApi' to class 'org.grails.datastore.gorm.mongo.api.MongoStaticApi'
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'org.grails.datastore.gorm.GormStaticApi@7af24f66' with class 'org.grails.datastore.gorm.GormStaticApi' to class 'org.grails.datastore.gorm.mongo.api.MongoStaticApi'
	at grails.mongodb.MongoEntity$Trait$Helper.currentMongoStaticApi(MongoEntity.groovy:263)
	at grails.mongodb.MongoEntity$Trait$Helper.createCriteria(MongoEntity.groovy:129)
	at org.grails.datastore.gorm.validation.constraints.UniqueConstraint.findExisting(UniqueConstraint.groovy:101)
	at org.grails.datastore.gorm.validation.constraints.UniqueConstraint.processValidate_closure1(UniqueConstraint.groovy:76)
	at org.grails.datastore.gorm.validation.constraints.UniqueConstraint.withManualFlushMode_closure4(UniqueConstraint.groovy:133)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.grails.datastore.gorm.GormStaticApi.withSession_closure21(GormStaticApi.groovy:819)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:318)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:40)
	at org.grails.datastore.gorm.GormStaticApi.withSession(GormStaticApi.groovy:818)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.withSession(GormEntity.groovy:889)
	at org.grails.datastore.gorm.validation.constraints.UniqueConstraint.withManualFlushMode(UniqueConstraint.groovy:128)
	at org.grails.datastore.gorm.validation.constraints.UniqueConstraint.processValidate(UniqueConstraint.groovy:46)
	at grails.validation.AbstractConstraint.validate(AbstractConstraint.java:107)
	at grails.validation.ConstrainedProperty.validate(ConstrainedProperty.java:979)
	at org.grails.validation.GrailsDomainClassValidator.validatePropertyWithConstraint(GrailsDomainClassValidator.java:206)
	at org.grails.validation.GrailsDomainClassValidator.validate(GrailsDomainClassValidator.java:81)
	at org.grails.datastore.gorm.GormValidationApi.doValidate(GormValidationApi.groovy:116)
	at org.grails.datastore.gorm.GormValidationApi.validate(GormValidationApi.groovy:197)
	at org.grails.datastore.gorm.GormValidateable$Trait$Helper.validate(GormValidateable.groovy:91)
	at org.grails.datastore.gorm.GormInstanceApi.doSave(GormInstanceApi.groovy:327)
	at org.grails.datastore.gorm.GormInstanceApi.save_closure5(GormInstanceApi.groovy:177)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:318)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:40)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:176)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:151)
	at testapp.FooSpec.test save(FooSpec.groovy:22)
```

**Comment by bessb** [comment]
I'm running into the exact same issue, except instead of a unique constraint I'm using the low-level API in `afterInsert()`. Using the same code as above, but removing the unique constraint and adding this:
```groovy
def afterInsert() {
    collection.update(['_id': id], [$set: [name: 'foo']])
}
```
```
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'org.grails.datastore.gorm.GormStaticApi@5b861ba0' with class 'org.grails.datastore.gorm.GormStaticApi' to class 'org.grails.datastore.gorm.mongo.api.MongoStaticApi'
	at grails.mongodb.MongoEntity$Trait$Helper.currentMongoStaticApi(MongoEntity.groovy:263)
	at grails.mongodb.MongoEntity$Trait$Helper.getCollection(MongoEntity.groovy:152)
	at testapp.Foo.afterInsert(Foo.groovy:9)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:201)
	at org.grails.datastore.gorm.events.DomainEventListener.invokeEvent(DomainEventListener.java:275)
	at org.grails.datastore.gorm.events.DomainEventListener.afterInsert(DomainEventListener.java:198)
	at org.grails.datastore.gorm.events.DomainEventListener.onPersistenceEvent(DomainEventListener.java:93)
	at org.grails.datastore.mapping.engine.event.AbstractPersistenceEventListener.onApplicationEvent(AbstractPersistenceEventListener.java:51)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337)
	at org.grails.datastore.mapping.engine.EntityPersister.firePostInsertEvent(EntityPersister.java:300)
	at org.grails.datastore.mapping.engine.NativeEntryEntityPersister.executeInsert(NativeEntryEntityPersister.java:1636)
	at org.grails.datastore.mapping.engine.NativeEntryEntityPersister$1.run(NativeEntryEntityPersister.java:835)
	at org.grails.datastore.mapping.core.impl.PendingOperationExecution.executePendingOperation(PendingOperationExecution.java:33)
	at org.grails.datastore.mapping.core.AbstractSession.flushPendingOperations(AbstractSession.java:416)
	at org.grails.datastore.mapping.core.AbstractSession.flushPendingInserts(AbstractSession.java:408)
	at org.grails.datastore.mapping.core.AbstractSession.flush(AbstractSession.java:322)
	at org.grails.datastore.gorm.GormInstanceApi.doSave(GormInstanceApi.groovy:353)
	at org.grails.datastore.gorm.GormInstanceApi.save_closure5(GormInstanceApi.groovy:177)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:318)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:40)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:176)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:151)
	at testapp.FooSpec.test save(FooSpec.groovy:22)
```

**Comment by chibigoku04** [comment]
I'm also running into the issue when trying to utilize `Foo.collection` in a service. This happens regardless of whether the domain is a unique constraint or not, however. I did not test if a Hibernate test would succeed. See https://github.com/chibigoku04/testapp/pull/1 for code causing this issue.

**Comment by jmmartin81** [comment]
Hi, I face same problem, anyone have some  workaround about this bug? regards

**Comment by kblief** [comment]
I am having the same issue.  I have to remove all my unit tests that use domain saving, like my services, and replace them with integration tests.

**Comment by puneetbehl** [comment]
This seems to be happening because of using SimpleMapDatastore which supports very simple and basic functionalities. I would suggest using `MongoDatastore` in the unit tests. For example, the test case would look like:
```
@TestFor(Foo)
class FooSpec extends MongoSpec {

    void "test save"() {
        given:
        new Foo(name: 'foo1', value: 'val1').save(flush: true, failOnError: true)

        expect:
        Foo.count == 1
    }

    @Override
    protected List<Class> getDomainClasses() {
        return super.getDomainClasses()  + [Foo]
    }
}
```

Read more about using MongoDB and unit testing [here](http://gorm.grails.org/latest/mongodb/manual/#testing)

**Comment by zsbenq** [comment]
@puneetbehl I tried your way but the issue is still there. I think my situation is that I used org.grails.plugins:build-test-data:3.0.1 build() function in my project. Its build() function doesn't use MongoDatastore.

**Comment by puneetbehl** [comment]
Maybe, but I tried with above sample application and it works.
