### ISSUE TITLE
grails 2.5.6 with mongo 6.1.2 unit tests don't run

### ISSUE THREAD

**Issue by jakecoffman** [grails/gorm-mongodb#44]
I tried to follow the instructions here: http://gorm.grails.org/6.1.2/mongodb/manual/#_removal_of_grails_datastore_simple

But I can't get the unit tests to run, I just get a stacktrace.

Example project here: https://github.com/jakecoffman/grails2mongo

Stacktrace when running unit tests: 

```
java.lang.AbstractMethodError: org.grails.datastore.mapping.core.AbstractDatastore.createSession(Lorg/springframework/core/env/PropertyResolver;)Lorg/grails/datastore/mapping/core/Session;
	at org.grails.datastore.mapping.core.AbstractDatastore.connect(AbstractDatastore.java:134)
	at org.grails.datastore.mapping.core.AbstractDatastore.connect(AbstractDatastore.java:130)
	at grails.test.runtime.DomainClassTestPlugin.connectDatastore(DomainClassTestPlugin.groovy:88)
	at grails.test.runtime.DomainClassTestPlugin.before(DomainClassTestPlugin.groovy:104)
	at grails.test.runtime.DomainClassTestPlugin.onTestEvent(DomainClassTestPlugin.groovy:123)
	at grails.test.runtime.TestRuntime.deliverEvent(TestRuntime.groovy:295)
	at grails.test.runtime.TestRuntime.processEvents(TestRuntime.groovy:264)
	at grails.test.runtime.TestRuntime.doPublishEvent(TestRuntime.groovy:248)
	at grails.test.runtime.TestRuntime.publishEvent(TestRuntime.groovy:211)
	at grails.test.runtime.TestRuntimeJunitAdapter.before(TestRuntimeJunitAdapter.groovy:109)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at grails.test.runtime.TestRuntimeJunitAdapter$1$2.evaluate(TestRuntimeJunitAdapter.groovy:47)
	at org.spockframework.runtime.extension.builtin.TestRuleInterceptor.intercept(TestRuleInterceptor.java:38)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:88)
	at org.spockframework.runtime.extension.builtin.AbstractRuleInterceptor$1.evaluate(AbstractRuleInterceptor.java:37)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at grails.test.runtime.TestRuntimeJunitAdapter$3$4.evaluate(TestRuntimeJunitAdapter.groovy:76)
	at org.spockframework.runtime.extension.builtin.ClassRuleInterceptor.intercept(ClassRuleInterceptor.java:38)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.codehaus.groovy.grails.test.spock.GrailsSpecTestType.doRun(GrailsSpecTestType.groovy:147)
	at org.codehaus.groovy.grails.test.support.GrailsTestTypeSupport.run(GrailsTestTypeSupport.groovy:121)
	at org.codehaus.groovy.grails.test.runner.GrailsProjectTestRunner.runTests(GrailsProjectTestRunner.groovy:415)
	at org.codehaus.groovy.grails.test.runner.GrailsProjectTestRunner.processTests(GrailsProjectTestRunner.groovy:395)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at org.codehaus.groovy.grails.test.runner.GrailsProjectTestRunner.runAllTests_closure7(GrailsProjectTestRunner.groovy:314)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.codehaus.groovy.grails.test.runner.GrailsProjectTestRunner.runAllTests(GrailsProjectTestRunner.groovy:300)
	at org.codehaus.groovy.grails.test.runner.GrailsProjectTestRunner.runAllTests(GrailsProjectTestRunner.groovy:215)
	at org.codehaus.groovy.grails.cli.fork.testing.ForkedGrailsTestRunner.runInstance(ForkedGrailsTestRunner.groovy:128)
	at org.codehaus.groovy.grails.cli.fork.ForkedGrailsProjectClassExecutor.run(ForkedGrailsProjectClassExecutor.groovy:74)
	at org.codehaus.groovy.grails.cli.fork.testing.ForkedGrailsTestRunner.main(ForkedGrailsTestRunner.groovy:75)
```

**Comment by jakecoffman** [comment]
I noticed 6.0.9 works. Shouldn't hibernate4 be using `grails-datastore-gorm-test` and not `grails-datastore-simple`?

**Comment by graemerocher** [comment]
`grails-datastore-simple` should be removed from the classpath

**Comment by jakecoffman** [comment]
@graemerocher I exclude `grails-datastore-simple` in the example project but the unit tests don't work.

**Comment by graemerocher** [comment]
almost certainly a dependency error, check your dependency graph with `dependency-report` and ensure your dependencies for `grails-datastore-` are all using 6.1.2

**Comment by jakecoffman** [comment]
@graemerocher Sorry, you were correct, `grails-datastore-simple` is getting pulled in from the inherited Grails dependencies. I added `excludes 'grails-datastore-simple'` in the `inherits("global")` block but it seems to have no effect. The docs only mention how to exclude from build.gradle. How do I exclude it from BuildConfig.groovy?

**Comment by jakecoffman** [comment]
@graemerocher I was able to get the unit tests running by excluding each individual plugin (`'grails-plugin-testing', 'grails-plugin-rest', 'grails-plugin-filters', 'grails-plugin-url-mappings', 'grails-plugin-async', 'grails-plugin-gsp'`) and then including them excluding `grails-datastore-simple`. 

https://github.com/jakecoffman/grails2mongo/blob/dep-fix/grails-app/conf/BuildConfig.groovy

However now I get some strange unit test failures. For example this line 405s instead of 200s: https://github.com/jakecoffman/grails2mongo/blob/dep-fix/test/unit/BookControllerSpec.groovy#L27

**Comment by puneetbehl** [comment]
@jakecoffman I think the main problem with the gorm-mongodb is solved. I would request to you open separate issue related to the last problem you mentioned with response code in Grails test library.
