### ISSUE TITLE
MappingBuilder DSL doesn't work

### ISSUE THREAD

**Issue by alvarosanchez** [grails/gorm-mongodb#51]
When using `grails.mongodb.mapping.MappingBuilder.document {}` DSL in a domain class, the following exception is produced:

```
    java.lang.ClassCastException: org.grails.datastore.mapping.keyvalue.mapping.config.Family cannot be cast to org.grails.datastore.mapping.mongo.config.MongoCollection
        at org.grails.datastore.mapping.config.AbstractGormMappingFactory.createMappedForm(AbstractGormMappingFactory.java:87)
        at org.grails.datastore.mapping.keyvalue.mapping.config.GormKeyValueMappingFactory.createMappedForm(GormKeyValueMappingFactory.java:39)
        at org.grails.datastore.mapping.keyvalue.mapping.config.GormKeyValueMappingFactory.createMappedForm(GormKeyValueMappingFactory.java:28)
        at org.grails.datastore.mapping.keyvalue.mapping.config.KeyValuePersistentEntity.<init>(KeyValuePersistentEntity.java:35)
        at org.grails.datastore.mapping.keyvalue.mapping.config.KeyValueMappingContext.createPersistentEntity(KeyValueMappingContext.java:96)
        at org.grails.datastore.mapping.model.AbstractMappingContext.addPersistentEntities(AbstractMappingContext.java:274)
        at grails.testing.gorm.DataTest$Trait$Helper.mockDomains(DataTest.groovy:75)
        at grails.testing.gorm.DataTest$Trait$Helper.mockDomain(DataTest.groovy:60)
        at grails.testing.gorm.DataTest$Trait$Helper.mockDomain(DataTest.groovy:59)
```

The mapping is defined as:

```groovy
    static final mapping = document {
        collection 'myCollection'
        sort Query.Order.asc('dateCreated')
    }
```

**Comment by graemerocher** [comment]
more accurate description would be that you cannot unit test MongoDB entities with `DataTest` since what is happening here is the unit testing APIs use a different config mechanism. Writing the test with `MongoSpec` would work for example

**Comment by alvarosanchez** [comment]
Yeah I realised in https://github.com/grails/grails-testing-support/issues/13

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/grails-data-mapping/commit/ae0e94733e4ec89f5f0e63dd1de80f9716bbc3ce
