### ISSUE TITLE
Cannot cast object '...' with class 'String' to class 'DirtyCheckable'

### ISSUE THREAD

**Issue by rahulsom** [grails/gorm-mongodb#58]
**Grails BugReport**: [rdbms_mongo-bug-report-06112017.zip](https://github.com/grails/gorm-mongodb/files/1448799/rdbms_mongo-bug-report-06112017.zip)
**Version**: Grails 3.3.1, GORM 6.1.7.RELEASE
**Worked in**: Grails 3.2.9, GORM 6.0.10.RELEASE

**Background**
I've got an app with Hibernate and Mongo. While my domain objects are slightly unusual (they implement a java interface and have methods that return Publishers), this code used to work with 3.2.9. Upgrading to 3.3.1 breaks it.

**Reproduction**
When I run `./grailsw run-app` or `./gradlew bootRun`, I get this exception

```
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '5a0146e9c4f090d4c3950012' with class 'java.lang.String' to class 'org.grails.datastore.mapping.dirty.checking.DirtyCheckable'
        at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:405)
        at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:319)
        at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:232)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:603)
        at org.grails.datastore.mapping.mongo.engine.MongoCodecEntityPersister.processAssociations(MongoCodecEntityPersister.groovy:327)
        at org.grails.datastore.mapping.mongo.engine.MongoCodecEntityPersister.persistEntity(MongoCodecEntityPersister.groovy:217)
        at org.grails.datastore.mapping.mongo.engine.MongoCodecEntityPersister.persistEntity(MongoCodecEntityPersister.groovy:534)
        at org.grails.datastore.mapping.engine.EntityPersister.persist(EntityPersister.java:183)
        at org.grails.datastore.mapping.core.AbstractSession.persist(AbstractSession.java:598)
        at org.grails.datastore.gorm.GormInstanceApi.doSave(GormInstanceApi.groovy:364)
        at org.grails.datastore.gorm.GormInstanceApi.doSave(GormInstanceApi.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Other info**
* @jameskleeh guided me through debugging it. Thanks!
We checked the property that gorm is trying to cast, and it turned out to be `id`.
* I tried replacing `String id` with `ObjectId id`. That didn't help much.

**Comment by rahulsom** [comment]
I suspect its the fact that the domain class implements an interface. When I remove that bit, i.e. 

```diff
-class PatientAccount implements JavaSnapshot<Long, Patient, String, Long, PatientEvent> {
+class PatientAccount {
```

and I remove the `@Override` annotations from that class, it starts up just fine.

**Comment by rahulsom** [comment]
Any chance to look at this? This is preventing me from upgrading a library to grails 3.3.

**Comment by graemerocher** [comment]
@puneetbehl please take a look
