### ISSUE TITLE
Domain not found in mapping context api when converting as JSON

### ISSUE THREAD

**Issue by mamunsrdr** [grails/gorm-mongodb#62]
When I'm trying to convert mongo entity using grails.converter.JSON, it's throwing the following exception `Could not retrieve the respective entity for domain Workspace in the mapping context API`. 
Dependency:
```
//grailsVersion 3.3.1
compile "org.grails.plugins:converters"
compile 'org.grails.plugins:mongodb:6.1.4'
compile "org.mongodb:mongodb-driver:3.5.0"
```

Domain class:
```
class Workspace {
    static mapWith = "mongo"

    ObjectId id
    String name
    List<ObjectId> formIds
    long companyId

    static mapping = {
        collection 'eform_workspace'
    }
}
```
Service code snippet:
```
List<Workspace> workspaces = Workspace.findAll()
String workspaceJson = workspaces as JSON // produces exception
return [
       workspacesJson: workspaceJson
]
```
Stacktrace:
```
Caused by: java.lang.RuntimeException: org.grails.core.exceptions.GrailsConfigurationException: Could not retrieve the respective entity for domain Workspace in the mapping context API
        at org.grails.web.converters.AbstractConverter.toString(AbstractConverter.java:120)
        at org.codehaus.groovy.runtime.typehandling.ShortTypeHandling.castToString(ShortTypeHandling.java:44)
        at com.example.artifact.form.service.EformHomeService$$EQcpF3wG.$tt__getUserWorkspaces(EformHomeService.groovy:14)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springsource.loaded.ri.ReloadedTypeInvoker$2.invoke(ReloadedTypeInvoker.java:133)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1462)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:925)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:908)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:76)
        at com.example.artifact.form.service.EformHomeService$_getUserWorkspaces_closure1$$EQcpF3wG.doCall(EformHomeService.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springsource.loaded.ri.ReloadedTypeInvoker$2.invoke(ReloadedTypeInvoker.java:133)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1462)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at groovy.lang.Closure.call(Closure.java:414)
        at com.example.artifact.form.service.EformHomeService$_getUserWorkspaces_closure1.call(EformHomeService.groovy)
        at groovy.lang.Closure.call(Closure.java:430)
        at com.example.artifact.form.service.EformHomeService$_getUserWorkspaces_closure1.call(EformHomeService.groovy)
        at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
        at com.example.artifact.form.service.EformHomeService$$EQcpF3wG.getUserWorkspaces(EformHomeService.groovy)
        at com.example.artifact.form.service.EformHomeService$$DQcpF3wG.getUserWorkspaces(Unknown Source)
        at com.example.artifact.form.service.EformHomeService.getUserWorkspaces(EformHomeService.groovy)
        at com.example.artifact.form.service.EformHomeService$getUserWorkspaces$0.call(Unknown Source)
        ... 98 common frames omitted
```

**Comment by mamunsrdr** [comment]
Duplicate: https://github.com/grails/grails-core/issues/10883
