### ISSUE TITLE
dbCollection.save() invokes the insert method internally

### ISSUE THREAD

**Issue by dreampursuer** [grails/gorm-mongodb#66]
I'm using the native mongodb driver to processing the data:
Grails version:grails3.3.2
Mongodb plugin:compile 'org.grails.plugins:mongodb:6.1.4'

```groovy
    def test(){
        def dbCollection = Stock.collection
        def queryObj = new BasicDBObject()
        def data = dbCollection.find(queryObj)
        for(row in data){
            row.remove("enabled")
            println "row:${row}"

            dbCollection.save(row)
        }
        render "ok"
    }
```

It throws the exception on duplicated _id index:
```groovy
Caused by: com.mongodb.MongoBulkWriteException: Bulk write operation error on server db.exphone.com:28018. Write errors: [BulkWriteError{index=0, code=11000, message='E11000 duplicate key error index: exphone2.stock.$_id_ dup key: { : ObjectId('58477c8cf38472d3a8f7fab8') }', details={ }}]. 
	at com.mongodb.connection.BulkWriteBatchCombiner.getError(BulkWriteBatchCombiner.java:176)
	at com.mongodb.connection.BulkWriteBatchCombiner.throwOnError(BulkWriteBatchCombiner.java:205)
	at com.mongodb.connection.BulkWriteBatchCombiner.getResult(BulkWriteBatchCombiner.java:146)
	at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:188)
	at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:168)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:426)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:417)
	at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:168)
	at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:74)
	at com.mongodb.Mongo.execute(Mongo.java:845)
	at com.mongodb.Mongo$2.execute(Mongo.java:828)
	at com.mongodb.MongoCollectionImpl.insertMany(MongoCollectionImpl.java:338)
	at com.mongodb.MongoCollectionImpl.insertMany(MongoCollectionImpl.java:322)
	at org.grails.datastore.gorm.mongo.extensions.MongoExtensions.insert(MongoExtensions.groovy:534)
	at org.grails.datastore.gorm.mongo.extensions.MongoExtensions.insert(MongoExtensions.groovy:481)
	at org.grails.datastore.gorm.mongo.extensions.MongoExtensions.save(MongoExtensions.groovy:583)
	at exphone.StockController$$EQhS2exz.test(StockController.groovy:114)
	... 14 common frames omitted
```
I found in the MongoExtensions.save()，it invokes the insert method internally.
I'm not sure it's a bug or not.

MongoExtensions.groovy
```groovy
    public static MongoCollection save(MongoCollection<Document> collection, Map<String, Object> document) {
        insert(collection, document);
        return (MongoCollection)ScriptBytecodeAdapter.castToType((Object)null, MongoCollection.class);
    }

    public static MongoCollection save(MongoCollection<Document> collection, Map<String, Object> document, WriteConcern writeConcern) {
        return insert(collection, document, writeConcern);
    }

    public static WriteResult save(DBCollection collection, Map document, WriteConcern writeConcern) {
        return collection.save((DBObject)(new BasicDBObject(document)), writeConcern);
    }
```

**Comment by puneetbehl** [comment]
I am assuming it will work fine when you do it as follows:
```
Stock.lis().each { stock->
 stock.enabled = false // or null
 stock.save()
}
````

Also, please share the sample application with example.

**Comment by dreampursuer** [comment]
Your code works fine. 
But I'm using the native Mongodb method to save the data by Stock.collection.save() will failed.
You can insert any data in the Stock collection and the testing code example is:
```
    def test(){
        def dbCollection = Stock.collection
        def queryObj = new BasicDBObject()
        def data = dbCollection.find(queryObj)
        for(row in data){
            row.remove("enabled")
            println "row:${row}"

            dbCollection.save(row)
        }
        render "ok"
    }
```

**Comment by puneetbehl** [comment]
I believe you cannot insert a new document with existing `_id`. Also, regarding the save method which is not a bug and instead you should use 
```
dbCollection.updateMany(query, ['$unset': [(fieldName): ""]] as Map<String, Object>)
```

**Tip:** Move all your update code into a service. Controller should not have all this code.
