### ISSUE TITLE
Issue With mongodb low level query

### ISSUE THREAD

**Issue by VikramSMalik** [grails/gorm-mongodb#69]
I'm using Grails 3.3.2 and mongodb:6.1.5 
I need atomic operation for generate sequenceId for this earlier version of Grails 2.5.4 i'm using `findAndModifiy()` mongodb low level API. but this same this is not working in grails 3.3.2

given missing method exception
Code
```
def getNextSequence(String name) {
        try {
            BasicDBObject find = new BasicDBObject();
            find.put("_id", name);
            BasicDBObject update = new BasicDBObject();
            update.put("\$inc", new BasicDBObject("seq", 1));
            def obj =  SequenceId.collection.findAndModify(find, update);
            if(obj==null){
                obj=createSequence(name)
            }
            return obj.seq
        } catch (Exception e){
            log.error("Error in Next Sequence",e)
        }
    }
```

Error 
```
groovy.lang.MissingMethodException: No signature of method: com.mongodb.MongoCollectionImpl.findAndModify() is applicable for argument types: (com.mongodb.BasicDBObject, com.mongodb.BasicDBObject) values: [[_id:masterOrderId], [$inc:[seq:1]]]
                at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
                at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:49)
                at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
                at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
                at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
                at com.lakshya.CheckoutService$$EQn1KIag.getNextSequence(CheckoutService.groovy:2053)
                at com.lakshya.CheckoutService$$DQn1KIag.getNextSequence(Unknown Source)
                at com.lakshya.CheckoutService.getNextSequence(CheckoutService.groovy)
                at com.lakshya.CheckoutService$$EQn1KIag.getMasterOrderId(CheckoutService.groovy:2038)
                at com.lakshya.CheckoutService$$DQn1KIag.getMasterOrderId(Unknown Source)
                at com.lakshya.CheckoutService.getMasterOrderId(CheckoutService.groovy)
                at com.lakshya.CheckoutService$$EQn1KIag.createOrder(CheckoutService.groovy:455)
                at com.lakshya.CheckoutService$$DQn1KIag.createOrder(Unknown Source)
                at com.lakshya.CheckoutService.createOrder(CheckoutService.groovy)
                at com.lakshya.CheckoutService$$FastClassBySpringCGLIB$$de8b43c7.invoke(<generated>)
                at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
                at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
                at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
                at org.aspectj.lang.ProceedingJoinPoint$proceed.call(Unknown Source)
                at com.ratetag.aspect.PerformanceMonitorAspect.profileService(PerformanceMonitorAspect.groovy:95)
                at sun.reflect.GeneratedMethodAccessor326.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:50)
                at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1462)
                at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
                at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
                at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
                at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
                at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
                at com.lakshya.CheckoutService$$EnhancerBySpringCGLIB$$283ee091.createOrder(<generated>)
                at com.lakshya.CheckoutService$createOrder.call(Unknown Source)
                at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
                at com.lakshya.CheckoutService$createOrder.call(Unknown Source)
                at 
```

**Comment by puneetbehl** [comment]
`MongoCollectionImpl` is the class from the MongoDB driver so you need to update the implementations as per latest MongoDB driver before the upgrade.

**Comment by puneetbehl** [comment]
Read the MongoDB driver documentation [here](https://mongodb.github.io/mongo-java-driver/) and I think the underline driver version for GORM MongoDB 6.1.5 is `3.5.0`.

**Comment by VikramSMalik** [comment]
Thanks Puneet 
yes i did i used findoneAndUpdate() method which is working
