### ISSUE TITLE
Application failed when we run integration or functional tests in grails mongodb

### ISSUE THREAD

**Issue by sadasivaiahgoli** [grails/gorm-mongodb#81]
[symload3.zip](https://github.com/grails/gorm-mongodb/files/2441629/symload3.zip)
Iam using grails 3.3.8 . Using gorm mongodb. I wrote one functional test case and one integraion test.
When I run test cases my mongodb server is shutting down and it will throw the following exceptions.I was attached the example in the above zip file ,it will reproduce the exceptions.

My Environments are
Linux 18 mint operation systems
MongoDB version 3.4.17
grailsVersion=3.3.8
gormVersion=6.1.10.RELEASE
gradleWrapperVersion=3.5
java version "1.8.0_181"

```
:integrationTestClasses
:integrationTest

com.symfore.core.SampleSpec > classMethod FAILED
    java.lang.NoClassDefFoundError
        Caused by: java.lang.ClassNotFoundException

com.symfore.core.HomeSpec > test something FAILED
    com.mongodb.MongoTimeoutException
Exception in thread "Thread-5" 2018-10-03 16:04:21.312  INFO --- [      Thread-15] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@a2b4120: startup date [Wed Oct 03 16:03:46 IST 2018]; root of context hierarchy
java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
        at de.flapdoodle.embed.process.io.file.Files.forceDelete(Files.java:119)
        at de.flapdoodle.embed.process.extract.ExtractedFileSets.delete(ExtractedFileSets.java:76)
        at de.flapdoodle.embed.process.store.ExtractedArtifactStore.removeFileSet(ExtractedArtifactStore.java:147)
        at de.flapdoodle.embed.process.runtime.Executable.stop(Executable.java:77)
        at de.flapdoodle.embed.process.runtime.Executable$JobKiller.run(Executable.java:90)
        at java.lang.Thread.run(Thread.java:745)
2018-10-03 16:04:21.426  INFO --- [      Thread-10] d.f.e.process.runtime.ProcessControl     : stopOrDestroyProcess: process hasn't exited 
Exception in thread "Thread-10" java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
        at de.flapdoodle.embed.process.io.file.Files.forceDelete(Files.java:119)
        at de.flapdoodle.embed.mongo.MongodProcess.deleteTempFiles(MongodProcess.java:92)
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.cleanupInternal(AbstractMongoProcess.java:124)
        at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:172)
        at de.flapdoodle.embed.process.runtime.Executable.stop(Executable.java:73)
        at de.flapdoodle.embed.process.runtime.Executable$JobKiller.run(Executable.java:90)
        at java.lang.Thread.run(Thread.java:745)

2 tests completed, 2 failed
:integrationTest FAILED
:mergeTestReports

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integrationTest'.
> There were failing tests. See the results at: file:///home/syms3/siva/grailsproj/symload3/build/test-results/integrationTest/

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by puneetbehl** [comment]
It seems to be related to embedded-mongo. Please report to https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo
